CREATE TABLE kits (
  id INTEGER PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  grade TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  user_id INTEGER NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX idx_kits_user_id ON kits(user_id);
CREATE INDEX idx_kits_status ON kits(status);
